.\" -*- nroff -*-
.ds g \" empty
.ds G \" empty
.\" Like TP, but if specified indent is more than half
.\" the current line-length - indent, use the default indent.
.de Tp
.ie \\n(.$=0:((0\\$1)*2u>(\\n(.lu-\\n(.iu)) .TP
.el .TP "\\$1"
..
.TH slapt-get 8 
.SH NAME
slapt-get \- frontend to pkgtools
.SH SYNOPSIS
.B slapt-get
[
.B option(s)
]
[
.BI target
]
.LP
.B options:
[
.B --download-only
]
[
.B --simulate|-s
]
[
.B --no-prompt|-y
]
[
.B --reinstall
]
[
.B --ignore-excludes
]
[
.B --no-md5
]
[
.B --no-dep
]
[
.B --disable-dep-check
]
[
.B --print-uris
]
[
.B --show-stats|-S
]
[
.B --config []
]
.LP
.B targets:
[
.B --update
]
[
.B --upgrade
]
[
.B --dist-upgrade
]
[
.B --install
]
[
.B --remove
]
[
.B --show
]
[
.B --search
]
[
.B --list
]
[
.B --installed
]
[
.B --clean
]
[
.B --autoclean
]
[
.B --version
]
.SH DESCRIPTION
.B slapt-get
is an APT like system for Slackware package management.  It
allows one to search for packages, install them, and upgrade the
installed packages all with a few simple commands.  Additional
features include listing all available packages, listing all
installed packages, and removing installed packages.
.B slapt-get
tries to emulate Debian's apt-get as closely as possible.
.SH OPTIONS
.TP
.B --download-only
Download the package only.  Do not install/upgrade.  Packages are downloaded to /var/slapt-get/.
.TP
.B --simulate|-s
Will not install or download packages.
.TP
.B --no-prompt|-y
Do not prompt for package upgrade confirmation.
.TP
.B --reinstall
Install the package even if it is already installed.
.TP
.B --ignore-excludes
Ignore exclude list and install excluded packages anyway.
.TP
.B --no-md5
Do not perform MD5 check sum on package.  This is dangerous!
.TP
.B --no-dep
Ignore dependency failures on --install, --upgrade, or --dist-upgrade
.TP
.B --disable-dep-check
Skip the dependency check (where available)
.TP
.B --print-uris
Print URIs of packages to be downloaded to stdout, but do not download.
.TP
.B --show-stats|-S
Show the download statistics
.TP
.B --config []
Specify file location of slapt-get configuration.  This overrides the default location, /etc/slapt-get/slapt-getrc.
.SH TARGETS
.TP
.B --update
Retrieves package data from MIRROR location.
.TP
.B --upgrade
Upgrade installed packages if newer versions are available.
.TP
.B --dist-upgrade
Upgrade to newer Slackware release.  This is the same as --upgrade, with the addition of checking to make sure that all the base packages, from the base disk set, are also installed.  Prior to running dist-upgrade, make sure that the package cache is updated and the crucial packages (glibc-solibs, sed, and pkgtools) are upgraded.  See UPGRADE.TXT on your local Slackware mirror.
.TP
.B --install [package(s)]
Install specified package(s).
.TP
.B --remove [package(s)]
Remove specified package(s).
.TP
.B --show [package]
Show package description.
.TP
.B --search [expression]
Search available packages. Applies POSIX and extended regular expression
to the names, locations, and descriptions of packages.
.TP
.B --list
List available packages.
.TP
.B --installed
List installed packages.
.TP
.B --clean
Purge cached/downloaded packages from /var/slapt-get/.
.TP
.B --autoclean
Purge duplicate older versions of cached/downloaded packages from /var/slapt-get/.
.TP
.B --version
Print version and license info.
.SH AUTHOR
Jason Woodward <woodwardj@jaos.org>
.SH "SEE ALSO"
.BR installpkg(8),
.BR makepkg(8),
.BR removepkg(8),
.BR explodepkg(8),
.BR pkgtool(8), 
.BR upgradepkg(8)
