.\" -*- nroff -*-
.ds g \" empty
.ds G \" empty
.\" Like TP, but if specified indent is more than half
.\" the current line-length - indent, use the default indent.
.de Tp
.ie \\n(.$=0:((0\\$1)*2u>(\\n(.lu-\\n(.iu)) .TP
.el .TP "\\$1"
..
.TH slapt-get 8 
.SH ИМЯ
slapt-get \- фронт-энд для pkgtools
.SH ИСПОЛЬЗОВАНИЕ
.B slapt-get
[
.B опции
]
[
.BI цель
]
.LP
.B опции:
[
.B --download-only|-d
]
[
.B --simulate|-s
]
[
.B --no-prompt|-y
]
[
.B --prompt|-p
]
[
.B --reinstall
]
[
.B --ignore-excludes
]
[
.B --no-md5
]
[
.B --ignore-dep
]
[
.B --no-dep
]
[
.B --print-uris
]
[
.B --show-stats|-S
]
[
.B --config|-c []
]
[
.B --remove-obsolete
]
[
.B --retry []
]
[
.B --no-upgrade
]
.LP
.B цели:
[
.B --update|-u
]
[
.B --upgrade
]
[
.B --dist-upgrade
]
[
.B --install|-i
]
[
.B --install-set
]
[
.B --remove
]
[
.B --show
]
[
.B --filelist
]
[
.B --search
]
[
.B --list
]
[
.B --available
]
[
.B --installed
]
[
.B --clean
]
[
.B --autoclean
]
[
.B --add-keys
]
[
.B --help|-h
]
[
.B --version
]
.SH ОПИСАНИЕ
.B slapt-get 
 - APT-подобная система для управления пакетами в Slackware.
Позволяет искать пакеты, устанавливать их и обновлять 
установленные пакеты при помощи нескольких простых 
комманд.
Дополнительные возможности включают в себя перечисление 
всех доступных пакетов, перечисление установленных пакетов и
удаление установленных пакетов.
.B slapt-get
пытается максимально имитировать поведение apt-get из Debian'а.
.SH ОПЦИИ
.TP
.B --download-only|-d
Только загрузить пакет. Не производить установку/обновление. Пакеты загружаются в /var/slapt-get/.
.TP
.B --simulate|-s
Симуляция. Не устанавливать и не скачивать пакеты.
.TP
.B --no-prompt|-y
Не запрашивать подтверждения на обновление/удаление пакета.
.TP
.B --prompt|-p
Всегда спрашивать подтверждения при установке пакета.
.TP
.B --reinstall
Установить пакет, даже если он уже установлен.
.TP
.B --ignore-excludes
Игнорировать список исключений и установить исключенные пакеты в любом случае.
.TP
.B --no-md5
Не проверять у пакета контрольную MD5-сумму. Использование этой опции небезопасно!
.TP
.B --ignore-dep
Игнорировать неудовлетворенные зависимости при --install, --upgrade, или --dist-upgrade
.TP
.B --no-dep
Пропустить проверку зависимостей.
.TP
.B --print-uris
Отобразить URI подлежащих загрузке пакетов, но не загружать их.
.TP
.B --show-stats|-S
Показать статистику загрузок.
.TP
.B --config|-c []
Указать размещение конфигурационного файла slapt-get. Конфигурационный файл по умолчанию, /etc/slapt-get/slapt-getrc, будет проигнорирован.
.TP
.B --remove-obsolete
Удалить пакеты, которые более недоступны. Работает только с --dist-upgrade и --remove. Будут удалены пакеты, которые уже недоступны ни на одном из указанных источников, но установлены в системе. Будьте осторожны, это также удалит отдельно собранные пакеты.  
.TP
.B --retry []
Указать количество повторных попыток в случае неудачной загрузки пакета.
.TP
.B --no-upgrade
Установить пакет, не пытаясь обнаружить и обновить предыдущую версию пакета. Полезно для пакетов ядра. Работает только вместе с опцией --install.
.SH ЦЕЛИ
.TP
.B --update|-u
Получить сведения о пакетах с адреса MIRROR.
.TP
.B --upgrade
Обновить установленные пакеты, если доступны новые версии.
.TP
.B --dist-upgrade
Обновить весь релиз Slackware. То же, что и --upgrade, плюс установка всех базовых пакетов с базового дискового набора. Перед использованием dist-upgrade убедитесь, что обновлён кэш пакетов и наиболее важные пакеты (glibc-solibs, sed и pkgtools). См. UPGRADE.TXT на зеркалах Slackware. 
.TP
.B --install|-i [пакет(ы)]
Установить указанные пакеты. Можно указать либо имя пакета, либо имя с версией (например, pkg-1.0-i386-1).
.TP
.B --install-set [дисковый(е) набор(ы)]
Установить указанные дисковые наборы. Пример: --install-set xap n l
.TP
.B --remove [пакет(ы)]
Удалить указанные пакеты. Можно указать либо имя пакета, либо имя с версией (например, pkg-1.0-i386-1).
.TP
.B --show [пакет(ы)]
Показать описание пакета. Можно указать либо имя пакета, либо имя с версией (например, pkg-1.0-i386-1).
.TP
.B --filelist [пакет(ы)]
Показать файлы установленные пакетом. Можно указать либо имя пакета, либо имя с версией (например, pkg-1.0-i386-1).
.TP
.B --search [выражение]
Искать доступные пакеты. Применяет POSIX- и расширенные регулярные выражения 
к именам, версиям, адресам и описаниям пакетов.
.TP
.B --list
Перечислить все пакеты, как установленные, так и доступные.
.TP
.B --available
Перечислить только досупные пакеты. Будут показаны пакеты, присутствующие на указанных вами источниках.
.TP
.B --installed
Перечислить только установленные пакеты.
.TP
.B --clean
Удалить кэшированные/загруженные пакеты из рабочего каталога WORKINGDIR (по умолчанию /var/slapt-get/).
.TP
.B --autoclean
Как и --clean, autoclean очищает локальный репозиторий полученных пакетов. Разница заключается в том, что будут удалены только те пакеты, которые уже не могут быть загружены, и в общем-то бесполезны. Это позволяет содержать кэш длительное время, не давая ему бесконтрольно разрастаться.
.TP
.B --add-keys
Проверить все источники пакетов на наличие файла GPG-KEY. Загрузить и импортировать в локальный список ключей.
.TP
.B --help|-h
Показать справку и выйти.
.TP
.B --version
Показать версию и лицензию.
.SH ПРИМЕЧАНИЯ
.TP
slapt-get использует pkgtools для установки, обновления и удаления.
.TP
slapt-get не строит предположений и не станет делать вещей, о которых его не просили.
.TP
slapt-get будет пытаться удовлетворить зависимости и разрешить конфликты только в тех пакетах, которые были собраны с соответствующей информацией. Официальные пакеты Slackware не содержат этой информации, поэтому опция --no-dep включена по умолчанию.
.TP
Непроверенные обновления рискованны как при использовании пакетов от сторонних разработчиков, так и при использовании официальных пакетов.
.TP
slapt-get не вносит в систему изменений, способных привести к тому, что вы не сможете использовать для каких-либо задач ничего, кроме slapt-get. В конфигурацию системы добавляются только /etc/slapt-get и /var/slapt-get. Ничто не мешает вам изпользовать другое решение или использовать upgradepkg вручную.
.TP
Стоит также прочесть UPGRADE.TXT и ChangeLog.txt; особенно ChangeLog.txt, если у вас релиз -current.

.SH ФАЙЛЫ
/etc/slapt-get/slapt-getrc

.SH АВТОР
Jason Woodward <woodwardj@jaos.org>
.SH ПЕРЕВОД
Иван Фитенко <digitalhunger@gmail.com>

.SH "СМ. ТАКЖЕ"
.BR installpkg(8),
.BR makepkg(8),
.BR removepkg(8),
.BR explodepkg(8),
.BR pkgtool(8), 
.BR upgradepkg(8),
.BR netrc(5)
